spring:
  application:
    name: seckill-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          # 本地 IDEA 运行，必须连 127.0.0.1，端口看你 docker-compose 映射
          url: jdbc:mysql://127.0.0.1:3307/seckill_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: root123
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          # 从库通常映射到 3308
          url: jdbc:mysql://127.0.0.1:3308/seckill_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: root123
          driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: seckill-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8083 # Product 端口